nitpweb/nitp-web-front

src/components/administration.js, src/components/administration/Navigate.js, src/components/administration/adcard.js, src/components/administration/const.js, src/components/administration/css/adcard.css, src/components/styles/AdminStyle.js, src/components/styles/NavigateStyle.js
director sir page is yet to add
=> admin page change

src/components/layout.css
Reverts nitpweb/nitp-web-front#97
=> Revert "fix"

src/components/home/gallery.js, src/components/home/styles.js
Changed Flex to grid structure
=> Fixed gallery rendering on home page

src/components/home.js, src/components/home/Innovation.js, src/components/home/homegif.js, src/components/home/newscard.js, src/components/home/styles.js, src/components/navbar.js, src/components/styles/eventcard.js, src/components/styles/newscard.js
- Alignment added in home/events section
- Capitalization of word "view more"
- More content added in news section
- Adding video component at footer in progress
=> Minor changes in font and alignment

src/components/global/dropdown.js, src/components/global/dropnew.js, src/components/home.js, src/components/isBrowser.js, src/components/navbar.js
- Logo reload many times done
- Each child has unique key prop error done
=> logo reload + key prop error

src/components/departments/arch/archhome.js, src/components/departments/ce/cehome.js, src/components/departments/chem/chemhome.js, src/components/departments/cse/csehome.js, src/components/departments/dephome.js, src/components/departments/ece/ecehome.js, src/components/departments/ee/eehome.js, src/components/departments/hss/hsshome.js, src/components/departments/math/mathhome.js, src/components/departments/me/mehome.js, src/components/departments/phy/phyhome.js, src/components/styles/facultycard.js
- Put Vision and Mission in the Last and Shift Syllabus and Faculty to the top immediately after “About”. 
- Email of web team overlap with designation
=> Changes in department section

src/components/Slider/SliderStyle.js, src/components/director.js
- Removed overlapping of director card with details div
- removed box shadow in activities page only
=> director page + slider

package.json, src/components/departments/arch/archhome.js, src/components/departments/ce/cehome.js, src/components/departments/chem/chemhome.js, src/components/departments/cse/csehome.js, src/components/departments/ece/ecehome.js, src/components/departments/ee/eehome.js, src/components/departments/hss/hsshome.js, src/components/departments/math/mathhome.js, src/components/departments/me/mehome.js, src/components/departments/phy/phyhome.js, src/components/home/importantlink.js, src/components/styles/home.js, yarn.lock
Reverts nitpweb/nitp-web-front#185
=> Revert "reduced notice section height"

src/components/departments/dephome.js, src/components/styles/tabpage.js
- Notice page overlapping of notices changed
=> Notice page overlap resolved

src/components/event.js, src/components/home.js, src/components/home/eventcard.js, src/components/styles/eventcard.js, src/components/styles/notice.js
- Event page and event component of home link working
- attachments to be done
=> event card and event page link working

src/components/director.js
- image overlapping in `/director` page fixed
=> director page image fixed

src/components/administration/const.js, src/components/facilities.js, src/pages/404.js
- Added form to electrical maintenance unit page
- Rewrite 404 page to redirect after 5s
- Updated name for disciplinary committee
=> Minor update

src/components/departments/ece/ecehome.js, src/components/departments/ece/ecesyllabus.js
=> ece dept. minor update

src/components/departments/math/mathsyllabus.js
=> Phd and dual degree in maths. dept.

src/components/global/facultyprofile.js
Hey there,
Please Merge into build.
=> fix:Faculty Qualification not visible in fac profile.

src/components/StaffClaimForms.js
=> Add: List of Hospital approved by BOG.

src/components/departments/faculty.js
- sorting function was not properly working
=> sorting of faculties changed

src/components/global/facultyprofile.js
=> fix:PG/UG Projects not visible on faculty profile.

src/components/home/nitpimg.js
=> slider images

src/components/home/importantlink.js, src/components/home/nitpimg.js
Changed  Innovation to Recruitment  and added the link of recruitment or jobs.
=> added recruitment  link

src/components/departments/arch/archhome.js, src/components/departments/ce/cehome.js, src/components/departments/chem/chemhome.js, src/components/departments/cse/csehome.js, src/components/departments/dephome.js, src/components/departments/ece/ecehome.js, src/components/departments/ee/eehome.js, src/components/departments/hss/hsshome.js, src/components/departments/math/mathhome.js, src/components/departments/me/mehome.js, src/components/departments/phy/phyhome.js, src/components/layout.css
=> added pictures of hod to each respective department and changed layout.

src/components/administration/const.js
=> added dean and service unit in Administration

src/components/departments/arch/archhome.js, src/components/departments/ce/cehome.js, src/components/departments/chem/chemhome.js, src/components/departments/cse/csehome.js, src/components/departments/dephome.js, src/components/departments/ece/ecehome.js, src/components/departments/ee/eehome.js, src/components/departments/hss/hsshome.js, src/components/departments/math/mathhome.js, src/components/departments/me/mehome.js, src/components/departments/phy/phyhome.js, src/components/layout.css
=> Added All HOD's pictures and changed layout

src/components/academics/acadData.js
=> Admission form links changed in acaedmic section

src/components/academics/acadData.js
=> Added 2 links back to format section of academics

src/components/global/navlist.js, src/pages/centreOfExcellence.js, src/pages/isro-racs.js
=> Added isro racs page

src/components/academics.js, src/components/academics/acadData.js, src/components/footer.js
=> Removed disconnected Numbers and added required links in COE section of academics

src/components/academics/IsroRac.js, src/components/academics/isroHome.js, src/pages/isro-racs.js
=> Added a new Section ISRO RAC in Academics and made a separate tab for it.

src/components/academics/acadData.js
This reverts commit 8ae03dd6a17646f98953573ed263dbea74ba3141.
=> "add information in admissions section"

src/components/administration/const.js, src/components/internationalAffairs/InternationalAffairs.js
=> Administration data update

src/components/administration/const.js, src/components/student/clubs.js
=> club section data added

src/components/home/notice.js
=> Changed display of notices

src/components/home/nitpBackImages/images.json
=> slider image update

src/components/internationalAffairs/InternationalAffHome.js, src/components/internationalAffairs/InternationalAffairs.js
=> International aff modification

src/components/academics/acadData.js, src/components/administration/const.js
=> update in academic session

src/components/home/nitpBackImages/images.json
=> slider  img update

src/components/home/notice.js
=> Made notices blink

src/components/global/navlist.js, src/components/student.js, src/components/student/const.js, src/components/student/floatmenu.js
=> Unnat bharat tab added

src/components/footer.js, src/pages/grievance.js
Page added in footer others section
Please review and merge
=> grievance cell page added 

src/components/home/notice.js
=> Changed blink color of notices

src/components/facilities.js, src/components/global/navlist.js
=> SC ST page added

src/components/home/notice.js
=> Changed notice blink time to assure blinking is visible

src/components/administration/const.js
=> BOG changes

src/components/administration/const.js
slight change in BOG  plz...  merge
=> Administration section BOG

src/components/navbar.js
=> Replaced old website link with the intranet website link

src/components/academics/acadData.js
=> phd data update

src/components/administration/const.js, src/components/departments/arch/archhome.js
=> Arch-department-update
